Context effects
TheEmidee/UE4GameBaseFramework pull request #160
Opened 2023-09-18 13:27 UTC by VectorGamez

2023-09-18 18:18 UTC, TheEmidee requested changes

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +#include "Components/SkeletalMeshComponent.h"
<> for the 2 lines

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +    if ( mesh_comp )
!= nullptr

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +    if ( mesh_comp )
actually you should revert the condition to reduce nesting

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +        if ( auto * owning_actor = mesh_comp->GetOwner() )
same here

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +            for ( const auto component : owning_actor->GetComponents() )
auto * ?

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +                if ( component )
!= nullptr

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +                if ( context_effect_implementing_object )
!= nullptr

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +                        ( bAttached ? SocketName : FName( "None" ) ),
you can use `NAME_None`

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +            if ( bPreviewInEditor )
invert condition

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +                if ( world && world->WorldType == EWorldType::EditorPreview )
world != nullptr

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +                if ( world && world->WorldType == EWorldType::EditorPreview )
could also invert the condition

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +                if ( world && world->WorldType == EWorldType::EditorPreview )
all the conditions could be inverted in fact in this function

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +                            if ( effect_library && effect_library->GetContextEffectsLibraryLoadState() == EGBFContextEffectsLibraryLoadState::Loaded )
effect library should always be valid here otherwise it would crash the line above

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFContextEffectsComponent.cpp
> +    const FHitResult hit_result,
const &

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFContextEffectsComponent.cpp
> +        if ( active_audio_component )
!= nullptr

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFContextEffectsComponent.cpp
> +        if ( active_niagara_component )
!= nullptr

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFContextEffectsComponent.cpp
> +void UGBFContextEffectsComponent::UpdateEffectContexts( const FGameplayTagContainer new_effect_contexts )
const &

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFContextEffectsLibrary.cpp
> +void UGBFContextEffectsLibrary::GetEffects( const FGameplayTag effect, const FGameplayTagContainer context, TArray< USoundBase * > & sounds, TArray< UNiagaraSystem * > & niagara_systems )
const ref for context

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFContextEffectsSubsystem.cpp
> +void UGBFContextEffectsSubsystem::SpawnContextEffects( const AActor * spawning_actor,
I would prefer you create a new structure to hold all these informations

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFContextEffectsSubsystem.cpp
> +void UGBFContextEffectsSubsystem::SpawnContextEffects( const AActor * spawning_actor,
Also input parameters (audio_out and niagara_out) should come first

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFContextEffectsSubsystem.cpp
> +bool UGBFContextEffectsSubsystem::GetContextFromSurfaceType( const TEnumAsByte< EPhysicalSurface > physical_surface, FGameplayTag & context )
context should be first

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Public/Feedback/ContextEffects/GBFContextEffectsComponent.h
> +    UPROPERTY( EditAnywhere )
those 2 properties should be private

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Public/Feedback/ContextEffects/GBFContextEffectsInterface.h
> +    void AnimMotionEffect( const FName bone,
use a structure here too

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Public/Feedback/ContextEffects/GBFContextEffectsLibrary.h
> +    void GetEffects( const FGameplayTag effect, const FGameplayTagContainer context, TArray< USoundBase * > & sounds, TArray< UNiagaraSystem * > & niagara_systems );
input params first

2023-09-18 18:18 UTC, TheEmidee commented on Source/GameBaseFramework/Public/Feedback/ContextEffects/GBFContextEffectsLibrary.h
> +    TArray< FGBFContextEffects > ContextEffects;
private

2023-09-19 07:48 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +#include "Components/SkeletalMeshComponent.h"
Done.

2023-09-19 07:48 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +    if ( mesh_comp )
Done.

2023-09-19 07:51 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +        if ( auto * owning_actor = mesh_comp->GetOwner() )
Done.

2023-09-19 07:51 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +            for ( const auto component : owning_actor->GetComponents() )
Done.

2023-09-19 07:51 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFAnimNotify_ContextEffects.cpp
> +                if ( component )
Done.

2023-09-19 07:53 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Feedback/ContextEffects/GBFContextEffectsSubsystem.cpp
> +bool UGBFContextEffectsSubsystem::GetContextFromSurfaceType( const TEnumAsByte< EPhysicalSurface > physical_surface, FGameplayTag & context )
Done.

2023-09-19 07:54 UTC, VectorGamez commented on Source/GameBaseFramework/Public/Feedback/ContextEffects/GBFContextEffectsComponent.h
> +    UPROPERTY( EditAnywhere )
Done.

2023-09-19 08:29 UTC, VectorGamez commented on Source/GameBaseFramework/Public/Feedback/ContextEffects/GBFContextEffectsInterface.h
> +    void AnimMotionEffect( const FName bone,
Done.

2023-09-19 08:30 UTC, Frickerson commented on Source/GameBaseFramework/Public/Feedback/ContextEffects/GBFContextEffectsLibrary.h
> +    void GetEffects( const FGameplayTag effect, const FGameplayTagContainer context, TArray< USoundBase * > & sounds, TArray< UNiagaraSystem * > & niagara_systems );
Done.

2023-09-19 08:31 UTC, VectorGamez commented on Source/GameBaseFramework/Public/Feedback/ContextEffects/GBFContextEffectsLibrary.h
> +    TArray< FGBFContextEffects > ContextEffects;
Done.

2023-09-25 10:29 UTC, TheEmidee approved these changes

2023-09-25 10:29 UTC, merged