Ue5.3
TheEmidee/UE4GameBaseFramework pull request #162
Opened 2023-09-18 15:16 UTC by VectorGamez

2023-09-18 18:38 UTC, TheEmidee requested changes

2023-09-18 18:38 UTC, TheEmidee commented on Source/GameBaseFramework/Private/GameFeatures/GBFGameFeatureAction_AddInputContextMapping.cpp
> +    if ( ensure( local_player ) )
!= nullptr

invert the condition also

2023-09-18 18:38 UTC, TheEmidee commented on Source/GameBaseFramework/Private/GameFeatures/GBFGameFeatureAction_AddInputContextMapping.cpp
> +    if ( ensure( local_player ) )
!= nullptr + invert condition

2023-09-18 18:38 UTC, TheEmidee commented on Source/GameBaseFramework/Private/GameFeatures/GBFGameFeatureAction_AddWidget.cpp
> +#include "Misc/DataValidation.h"
<>

2023-09-18 18:38 UTC, TheEmidee commented on Source/GameBaseFramework/Private/GameFramework/Phases/GBFGamePhaseAbility.cpp
> +#include "Misc/DataValidation.h"
<>

2023-09-19 07:43 UTC, VectorGamez commented on Source/GameBaseFramework/Private/GameFeatures/GBFGameFeatureAction_AddInputContextMapping.cpp
> +    if ( ensure( local_player ) )
Done.

2023-09-19 07:45 UTC, VectorGamez commented on Source/GameBaseFramework/Private/GameFeatures/GBFGameFeatureAction_AddInputContextMapping.cpp
> +    if ( ensure( local_player ) )
Done.

2023-09-19 07:45 UTC, VectorGamez commented on Source/GameBaseFramework/Private/GameFeatures/GBFGameFeatureAction_AddWidget.cpp
> +#include "Misc/DataValidation.h"
Done.

2023-09-19 07:45 UTC, VectorGamez commented on Source/GameBaseFramework/Private/GameFramework/Phases/GBFGamePhaseAbility.cpp
> +#include "Misc/DataValidation.h"
Done.

2023-09-19 20:16 UTC, TheEmidee approved these changes

2023-09-25 10:20 UTC, merged