splitscreen_layout_subsystem
TheEmidee/UE4GameBaseFramework pull request #195
Opened 2023-11-30 17:07 UTC by TheEmidee

2023-12-01 09:01 UTC, VectorGamez approved these changes

2023-12-01 11:23 UTC, Frickerson requested changes

2023-12-01 11:23 UTC, VectorGamez commented on Source/GameBaseFramework/Public/GameFramework/GBFLocalMultiplayerSubsystem.h
> +#include "EnhancedInputSubsystemInterface.h"
<>

2023-12-05 08:46 UTC, VectorGamez approved these changes

2023-12-05 09:14 UTC, TheEmidee reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/195)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @TheEmidee and @VectorGamez)

___
*[`Source/GameBaseFramework/Public/GameFramework/GBFLocalMultiplayerSubsystem.h` line 3 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/195#gh-1411961428:-NktFVoC-X2rFd8AR2SL:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/4986b3ee1bb5fb208ecf76542599255201300d5c/Source/GameBaseFramework/Public/GameFramework/GBFLocalMultiplayerSubsystem.h#L3)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

<>
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-05 09:15 UTC, merged