Added texture validator
TheEmidee/UE4GameBaseFramework pull request #21
Opened 2020-12-04 15:50 UTC by TheEmidee

2020-12-04 15:57 UTC, VectorGamez commented on Source/GameBaseFrameworkEditor/Private/DataValidation/GBFValidatorTexturesBase.cpp
> +    auto * texture = Cast< UTexture >( in_asset );
const auto *

2020-12-04 16:06 UTC, Eldoir requested changes

2020-12-04 16:06 UTC, Eldoir commented on Source/GameBaseFrameworkEditor/Private/DataValidation/GBFValidatorTexturesBase.cpp
> +    auto * texture = Cast< UTexture >( in_asset );
const ?

2020-12-09 15:18 UTC, TheEmidee reviewed
> *[Reviewable](https://reviewable.io/reviews/theemidee/ue4gamebaseframework/21)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @TheEmidee and @VectorGamez)

___
*[Source/GameBaseFrameworkEditor/Private/DataValidation/GBFValidatorTexturesBase.cpp, line 65 at r1](https://reviewable.io/reviews/theemidee/ue4gamebaseframework/21#-MO0NfOOPPQ5B9fFCbM3-r1-65:-MO74C-a10SiE67hyW-j:b-896fix) ([raw file](https://github.com/theemidee/ue4gamebaseframework/blob/be525cacb5e6bbf7a16630db7be2a0c7208e8bd8/Source/GameBaseFrameworkEditor/Private/DataValidation/GBFValidatorTexturesBase.cpp#L65)):*
<details><summary><i>Previously, Eldoir (Arthur Cousseau) wrote…</i></summary><blockquote>

const ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-09 15:19 UTC, merged