game_phase_tasks
TheEmidee/UE4GameBaseFramework pull request #219
Opened 2024-01-09 22:10 UTC by TheEmidee

- Made functions that observe phase start or end return a handle
- Added BP tasks to observe the start or end of game phases

2024-01-10 09:32 UTC, VectorGamez requested changes

2024-01-10 09:32 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Phases/GBFGamePhaseSubsystem.cpp
> +        for ( auto index = 0; index < PhaseStartObservers.Num(); ++index )
could keep the foreach?

2024-01-10 09:32 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Phases/GBFGamePhaseSubsystem.cpp
> +    for ( auto index = 0; index < PhaseEndObservers.Num(); ++index )
Same

2024-01-10 19:18 UTC, TheEmidee reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/219)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @VectorGamez)

___
*[`Source/GameBaseFramework/Private/Phases/GBFGamePhaseSubsystem.cpp` line 270 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/219#gh-1447109711:-NnonvXiAqja6LXHnTfc:bvd93x1) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/a6c74bdc24e6088b94c886d93d525627477f0728/Source/GameBaseFramework/Private/Phases/GBFGamePhaseSubsystem.cpp#L270)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

could keep the foreach?
</blockquote></details>

I need the index


<!-- Sent from Reviewable.io -->

2024-01-10 19:18 UTC, TheEmidee reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/219)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @TheEmidee and @VectorGamez)

___
*[`Source/GameBaseFramework/Private/Phases/GBFGamePhaseSubsystem.cpp` line 300 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/219#gh-1447110169:-NnonyIXE8C9zLyWeKVQ:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/a6c74bdc24e6088b94c886d93d525627477f0728/Source/GameBaseFramework/Private/Phases/GBFGamePhaseSubsystem.cpp#L300)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-11 08:10 UTC, VectorGamez requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/219)* status: all files reviewed, 2 unresolved discussions (waiting on @TheEmidee)

___
*[`Source/GameBaseFramework/Private/Phases/GBFGamePhaseSubsystem.cpp` line 270 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/219#gh-1447109711:-NnrZUrm7BtBWwwFjsyw:b5al5sd) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/a6c74bdc24e6088b94c886d93d525627477f0728/Source/GameBaseFramework/Private/Phases/GBFGamePhaseSubsystem.cpp#L270)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

I need the index
</blockquote></details>

It does not seem to be used right now though?


<!-- Sent from Reviewable.io -->

2024-01-11 09:32 UTC, TheEmidee reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/219)* status: all files reviewed, 2 unresolved discussions (waiting on @VectorGamez)

___
*[`Source/GameBaseFramework/Private/Phases/GBFGamePhaseSubsystem.cpp` line 270 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/219#gh-1447109711:-NnrrLpd6-9hmg6fEbKZ:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/a6c74bdc24e6088b94c886d93d525627477f0728/Source/GameBaseFramework/Private/Phases/GBFGamePhaseSubsystem.cpp#L270)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

It does not seem to be used right now though?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-11 10:41 UTC, merged