Wait actor in range task
TheEmidee/UE4GameBaseFramework pull request #229
Opened 2024-02-13 16:15 UTC by VectorGamez

2024-02-13 22:04 UTC, TheEmidee requested changes

2024-02-13 22:04 UTC, TheEmidee commented on Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitForActorToBeInRange.cpp
> +    my_obj->Range = range;
Directly set RangeSquared to avoid computing it each frame

2024-02-13 22:04 UTC, TheEmidee commented on Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitForActorToBeInRange.cpp
> +        if ( bTriggerOnce )
I think we don't want that, else it would broadcast each tick?

2024-02-13 22:18 UTC, TheEmidee reviewed
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/229)* status: all files reviewed, 2 unresolved discussions (waiting on @ThibNach and @VectorGamez)



<!-- Sent from Reviewable.io -->

2024-02-13 22:30 UTC, VectorGamez reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/229)* status: all files reviewed, 2 unresolved discussions (waiting on @TheEmidee and @ThibNach)

___
*[`Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitForActorToBeInRange.cpp` line 25 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/229#gh-1488642309:-NqZ_1Y46RopVlaouC1C:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/8b26b712816ac6ed672b70ce38cb58f2e18c3da7/Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitForActorToBeInRange.cpp#L25)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

Directly set RangeSquared to avoid computing it each frame
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitForActorToBeInRange.cpp` line 60 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/229#gh-1488642755:-NqZZmQb5ZVHZHuy-U2_:b-f81g02) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/8b26b712816ac6ed672b70ce38cb58f2e18c3da7/Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitForActorToBeInRange.cpp#L60)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

I think we don't want that, else it would broadcast each tick?
</blockquote></details>

Indeed, that might be too much.
Done.


<!-- Sent from Reviewable.io -->

2024-02-14 07:33 UTC, ThibNach approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/229#-:-NqaX9U79_OQNG1Sc6t-:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @TheEmidee and @VectorGamez)

___
*[`Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitForActorToBeInRange.cpp` line 21 at r3](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/229#-NqaWjD-7PS1TbtZuIQq:-NqaWjD-7PS1TbtZuIQr:b-wjq0k6) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/7bceab74715e3634c68202b83473f8e2f7559e4e/Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitForActorToBeInRange.cpp#L21)):*
> ```cpp
>     const FGBFAxesToCheck & axes_to_check )
> {
>     auto * my_obj = NewAbilityTask< UGBFAT_WaitForActorToBeInRange >( owning_ability );
> ```

is it OK to use generic names like my_obj,obj, index, ...?


<!-- Sent from Reviewable.io -->

2024-02-14 09:28 UTC, VectorGamez reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/229)* status: all files reviewed, 3 unresolved discussions (waiting on @MaxDaniels, @TheEmidee, and @ThibNach)

___
*[`Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitForActorToBeInRange.cpp` line 21 at r3](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/229#-NqaWjD-7PS1TbtZuIQq:-NqawKH2A2S3owyqLeZA:b-adkibh) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/7bceab74715e3634c68202b83473f8e2f7559e4e/Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_WaitForActorToBeInRange.cpp#L21)):*
<details><summary><i>Previously, ThibNach wrote…</i></summary><blockquote>

is it OK to use generic names like my_obj,obj, index, ...?
</blockquote></details>

I think in this case it is, since it's obvious what the variable is.


<!-- Sent from Reviewable.io -->

2024-02-14 09:38 UTC, TheEmidee approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/229#-:-NqaytBJ3Z1HTcDQq2m_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MaxDaniels and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-02-14 09:38 UTC, merged