Made GetTargetActor of GBFCameraMode blueprintable
TheEmidee/UE4GameBaseFramework pull request #234
Opened 2024-02-19 15:53 UTC by TheEmidee

2024-02-19 16:31 UTC, VectorGamez requested changes

2024-02-19 16:31 UTC, VectorGamez commented on Source/GameBaseFramework/Public/Camera/GBFCameraMode.h
> +    UFUNCTION( BlueprintNativeEvent, BlueprintCallable )
I think BlueprintPure would be better no?

2024-02-19 20:31 UTC, TheEmidee reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/234)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @VectorGamez)

___
*[`Source/GameBaseFramework/Public/Camera/GBFCameraMode.h` line 105 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/234#gh-1494809496:-Nr234E3Af9QsIjylUIJ:b-3gdur0) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/2ad774f080037de49184a3b80ed90a2653eed154/Source/GameBaseFramework/Public/Camera/GBFCameraMode.h#L105)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

I think BlueprintPure would be better no?
</blockquote></details>

Indeed. For some reason I thought I could not with the BlueprintNativeEvent...-


<!-- Sent from Reviewable.io -->

2024-02-20 09:10 UTC, VectorGamez approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/234#-:-Nr4lyBIBrv_e78WFzV9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TheEmidee)



<!-- Sent from Reviewable.io -->

2024-02-20 09:59 UTC, merged