Bt task activate ability timer update
TheEmidee/UE4GameBaseFramework pull request #237
Opened 2024-02-26 12:00 UTC by VectorGamez

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/237)

2024-02-26 12:23 UTC, ThibNach submitted a review, later dismissed

2024-02-26 13:36 UTC, TheEmidee requested changes

2024-02-26 13:36 UTC, TheEmidee commented on Source/GameBaseFramework/Private/AI/GBFBTTask_TryActivateAbility.cpp
> +    if ( blackboard_component != nullptr &&
put the `&&` at the beginning of the next lines

2024-02-26 13:36 UTC, TheEmidee commented on Source/GameBaseFramework/Public/AI/GBFBTTask_TryActivateAbility.h
> +    FBlackboardKeySelector TimeBlackboardKey;
I would name it so that it's clear that the ability will be cancelled after this time

2024-02-26 13:51 UTC, MaxDaniels approved these changes, later dismissed

2024-02-26 13:56 UTC, TheEmidee reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/237)* status: all files reviewed, 2 unresolved discussions (waiting on @VectorGamez)



<!-- Sent from Reviewable.io -->

2024-02-26 14:09 UTC, VectorGamez reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/237)* status: all files reviewed, 2 unresolved discussions (waiting on @TheEmidee)

___
*[`Source/GameBaseFramework/Private/AI/GBFBTTask_TryActivateAbility.cpp` line 214 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/237#gh-1502626402:-Nr_iYmLDNyyqqe9rGPI:bsgmlul) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/cff4744fe4b19c3ab3387bebd42dde726a25d23c/Source/GameBaseFramework/Private/AI/GBFBTTask_TryActivateAbility.cpp#L214)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

put the `&&` at the beginning of the next lines
</blockquote></details>

clang format does not allow that
___
*[`Source/GameBaseFramework/Public/AI/GBFBTTask_TryActivateAbility.h` line 57 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/237#gh-1502627776:-Nr_jGC06baTO3RHp9sz:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/cff4744fe4b19c3ab3387bebd42dde726a25d23c/Source/GameBaseFramework/Public/AI/GBFBTTask_TryActivateAbility.h#L57)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

I would name it so that it's clear that the ability will be cancelled after this time
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-27 09:48 UTC, TheEmidee approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/237#-:-NrdxmuY26rnPGZbOSeb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @VectorGamez)



<!-- Sent from Reviewable.io -->

2024-02-27 09:48 UTC, merged