multiple interactions on interactable target
TheEmidee/UE4GameBaseFramework pull request #242
Opened 2024-03-05 17:00 UTC by TheEmidee

Reworked interactions to allow an interactable target to propose multiple options
Support for tag filtering on the target or the instigator
Support for specific input mapping context or input action

2024-03-05 18:19 UTC, VectorGamez requested changes

2024-03-05 18:19 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Interaction/Abilities/GBFGameplayAbility_Interact.cpp
> +    for ( const auto context : BindActionHandles )
also reset array after for loop

2024-03-05 18:19 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Interaction/Abilities/GBFGameplayAbility_Interact.cpp
> +    InputConfigInfos.Reset();
InputMappingContextInfos instead

2024-03-05 18:19 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Interaction/Abilities/GBFGameplayAbility_Interact.cpp
> +    InputConfigInfos.Reset();
Already reset earlier

2024-03-05 18:19 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Interaction/GBFInteractableActor.cpp
> +#include "OnlineSubsystemTypes.h"
<>

2024-03-05 18:19 UTC, VectorGamez commented on Source/GameBaseFramework/Private/Interaction/GBFInteractionStatics.cpp
> +#include "AbilitySystemBlueprintLibrary.h"
<>

2024-03-06 08:03 UTC, ThibNach submitted a review, later dismissed

2024-03-06 14:26 UTC, merged