Split action bar
TheEmidee/UE4GameBaseFramework pull request #259
Opened 2024-04-26 14:32 UTC by ThibNach

Add Split Action Bar class to automaticaly display the back action in the left  of the bar if there is a back action registered and the others actions registered on the right of the bar

2024-04-29 08:51 UTC, VectorGamez requested changes

2024-04-29 08:51 UTC, Frickerson commented on Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp
> +#include "Engine/GameInstance.h"
<>
and some other engine includes here

2024-04-29 08:51 UTC, VectorGamez commented on Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp
> +        if ( UWidgetTree * widget_tree = Cast< UWidgetTree >( GetOuter() ) )
auto

2024-04-29 08:51 UTC, VectorGamez commented on Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp
> +            if ( UUserWidget * user_widget = Cast< UUserWidget >( widget_tree->GetOuter() ) )
same

2024-04-29 08:51 UTC, VectorGamez commented on Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp
> +                                const UInputAction * input_action = binding->InputAction.Get();
const auto *

2024-04-29 08:51 UTC, VectorGamez commented on Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp
> +    const ULocalPlayer * new_player = GetGameInstance()->GetLocalPlayerByIndex( player_id );
const auto *

2024-04-29 08:51 UTC, VectorGamez commented on Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h
> +#include "Components/HorizontalBox.h"
<>

2024-04-30 06:40 UTC, ThibNach commented on Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp
> +#include "Engine/GameInstance.h"
Done

2024-04-30 06:41 UTC, ThibNach commented on Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp
> +        if ( UWidgetTree * widget_tree = Cast< UWidgetTree >( GetOuter() ) )
Done

2024-04-30 06:41 UTC, ThibNach commented on Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp
> +            if ( UUserWidget * user_widget = Cast< UUserWidget >( widget_tree->GetOuter() ) )
Done

2024-04-30 06:41 UTC, ThibNach commented on Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp
> +                                const UInputAction * input_action = binding->InputAction.Get();
Done

2024-04-30 06:41 UTC, ThibNach commented on Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp
> +    const ULocalPlayer * new_player = GetGameInstance()->GetLocalPlayerByIndex( player_id );
Done

2024-04-30 06:41 UTC, ThibNach commented on Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h
> +#include "Components/HorizontalBox.h"
Done

2024-04-30 15:11 UTC, VectorGamez approved these changes, later dismissed

2024-05-06 09:48 UTC, TheEmidee requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259)* status: all files reviewed, 17 unresolved discussions (waiting on @Fr0oZzFred, @MaxDaniels, @ThibNach, and @VectorGamez)

___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 7 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#gh-1582666174:-NxCH28K7_2_1u41vC0w:bb7lgjf) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/46c09e618187ffd6041083f9490ccd574dc734ed/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L7)):*
<details><summary><i>Previously, ThibNach (Thibaut Spreux) wrote…</i></summary><blockquote>

Done
</blockquote></details>

nope
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 17 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCH4IO1ZupCJrHAUFe:-NxCH4IPAIK3_OPTbFtz:b-7vxhjk) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L17)):*
> ```cpp
> 
> bool bSplitActionBarIgnoreOptOut = false;
> static FAutoConsoleVariableRef CVarSplitActionBarIgnoreOptOut(
> ```

surround with `#if !UE_BUILD_SHIPPING`
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 54 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCHB9EEO_w3m4kpPcW:-NxCHB9EEO_w3m4kpPcX:b-fcp5xa) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L54)):*
> ```cpp
> bool UGBFSplitCommonBoundActionBar::IsEntryClassValid( TSubclassOf< UUserWidget > in_entry_class ) const
> {
>     if ( in_entry_class )
> ```

`!= nullptr`
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 92 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCHEJG2-hzfkq1-jpH:-NxCHEJG2-hzfkq1-jpI:b-pc7kko) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L92)):*
> ```cpp
> }
> 
> void UGBFSplitCommonBoundActionBar::SynchronizeProperties()
> ```

can be removed
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 151 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCHnbi7V7E5bProTWV:-NxCHnbi7V7E5bProTWW:b-fcp5xa) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L151)):*
> ```cpp
>     Super::ValidateCompiledDefaults( compile_log );
> 
>     if ( !ActionButtonClass )
> ```

`!= nullptr`
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 189 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCHwhr5o8Irf8rhoO_:-NxCHwhr5o8Irf8rhoOa:b-nzjuce) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L189)):*
> ```cpp
>     for ( const auto * local_player : sorted_players )
>     {
>         if ( local_player == owning_local_player || !bDisplayOwningPlayerActionsOnly )
> ```

invert all the conditions here and below to reduce nesting
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 303 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCIAEU6jFewW-J8uIm:-NxCIAEU6jFewW-J8uIn:bb7da9g) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L303)):*
> ```cpp
>                             }
> 
>                             const bool is_valid_action_a = legacy_data_a || input_action_a;
> ```

auto
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 308 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCI9_61pBIWYxRg7Gd:-NxCI9_61pBIWYxRg7Ge:bb7da9g) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L308)):*
> ```cpp
>                             if ( ensureMsgf( ( is_valid_action_a && is_valid_action_b ), TEXT( "Action bindings not displayed yet -- array filter enforces they are not included" ) ) )
>                             {
>                                 const bool a_is_back = is_key_back_action( legacy_data_a, input_action_a );
> ```

auto
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 316 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCIC8u8Ak_uKUNe_fC:-NxCIC8u8Ak_uKUNe_fD:bb7da9g) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L316)):*
> ```cpp
>                                 }
> 
>                                 const int32 nav_bar_priority_a = get_navbar_priority( legacy_data_a, input_action_a );
> ```

auto
___
*[`Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h` line 59 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCGyoz7P-ODM8eF8SK:-NxCGyoz7P-ODM8eF8SL:b-nokqql) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h#L59)):*
> ```objc
> 
>     UPROPERTY( EditAnywhere, AdvancedDisplay, Category = Display )
>     uint8 bIgnoreDuplicateActions : 1;
> ```

this is not used
___
*[`Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h` line 65 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCGAniCe4z1TiunNWk:-NxCGAniCe4z1TiunNWl:b-ae484u) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h#L65)):*
> ```objc
> 
>     UPROPERTY( BlueprintReadOnly, meta = ( AllowPrivateAccess, BindWidget ) )
>     TObjectPtr< UHorizontalBox > LeftHorizontalBox;
> ```

Keep it generic. Maybe someone will want to not put actions on the Left or the Right.
I would rename one `CancelButtonContainer` and the other one `ActionButtonsContainer`
___
*[`Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h` line 65 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCGmun8oikoLQaNV8m:-NxCGmuo2QNFwRgD9usB:bowm94o) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h#L65)):*
> ```objc
> 
>     UPROPERTY( BlueprintReadOnly, meta = ( AllowPrivateAccess, BindWidget ) )
>     TObjectPtr< UHorizontalBox > LeftHorizontalBox;
> ```

In the same spirit, some would want to use another container. Expose a `TObjectPtr< UPanelWidget >` for both


<!-- Sent from Reviewable.io -->

2024-05-13 08:04 UTC, ThibNach reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259)* status: all files reviewed, 17 unresolved discussions (waiting on @Fr0oZzFred, @MaxDaniels, @TheEmidee, and @VectorGamez)

___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 7 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#gh-1582666174:-Nxkjs2h-gHOk6htNEIh:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/46c09e618187ffd6041083f9490ccd574dc734ed/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L7)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

nope
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 17 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCH4IO1ZupCJrHAUFe:-Nxkk5Jx4pNw4s8BS0X3:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L17)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

surround with `#if !UE_BUILD_SHIPPING`
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 54 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCHB9EEO_w3m4kpPcW:-NxkkAPoElY83mvpHmZk:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L54)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

`!= nullptr`
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 92 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCHEJG2-hzfkq1-jpH:-NxkkItG9zaVNIJ7OygD:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L92)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

can be removed
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 151 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCHnbi7V7E5bProTWV:-NxkkTfI5l4XgMWdcvq0:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L151)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

`!= nullptr`
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 189 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCHwhr5o8Irf8rhoO_:-NxkruPnCDU1c0XqylPM:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L189)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

invert all the conditions here and below to reduce nesting
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 303 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCIAEU6jFewW-J8uIm:-NxkkdIJ4-Yxspdxh_ri:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L303)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 308 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCI9_61pBIWYxRg7Gd:-NxkkhEI4b3XeBKfY5y3:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L308)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 316 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCIC8u8Ak_uKUNe_fC:-NxkkmCp1VHv2ybdUPPL:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L316)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

auto
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h` line 59 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCGyoz7P-ODM8eF8SK:-NxklWWhE8wEgWYQOZ_C:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h#L59)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

this is not used
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h` line 65 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCGAniCe4z1TiunNWk:-NxknlkoDoBvvHvFlnzg:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h#L65)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

Keep it generic. Maybe someone will want to not put actions on the Left or the Right.
I would rename one `CancelButtonContainer` and the other one `ActionButtonsContainer`
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h` line 65 at r2](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxCGmun8oikoLQaNV8m:-Nxknlyf47ohiF3UuZDI:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/eb2845377a13989d58c032a77997adfc424976c2/Source/GameBaseFramework/Public/GBFSplitCommonBoundActionBar.h#L65)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

In the same spirit, some would want to use another container. Expose a `TObjectPtr< UPanelWidget >` for both
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-13 08:59 UTC, VectorGamez requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259)* status: all files reviewed, 12 unresolved discussions (waiting on @Fr0oZzFred, @MaxDaniels, and @TheEmidee)

___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 7 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#gh-1582666174:-Nxl9jVaCWdmuw6uAKy2:b-ypdhbl) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/46c09e618187ffd6041083f9490ccd574dc734ed/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L7)):*
<details><summary><i>Previously, ThibNach (Thibaut Spreux) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Missed "OnlineSubsystemUtils.h" ^^


<!-- Sent from Reviewable.io -->

2024-05-13 09:54 UTC, ThibNach reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259)* status: all files reviewed, 12 unresolved discussions (waiting on @Fr0oZzFred, @MaxDaniels, @TheEmidee, and @VectorGamez)

___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 7 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#gh-1582666174:-NxlMz8n0e7PJQjDWvEU:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/46c09e618187ffd6041083f9490ccd574dc734ed/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L7)):*
<details><summary><i>Previously, VectorGamez (Viktor Blomme) wrote…</i></summary><blockquote>

Missed "OnlineSubsystemUtils.h" ^^
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-13 12:55 UTC, VectorGamez submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-:-Nxm0Ujs7HajVxJpLN81:bnfp4nl)* status: all files reviewed, 11 unresolved discussions (waiting on @Fr0oZzFred, @MaxDaniels, and @TheEmidee)



<!-- Sent from Reviewable.io -->

2024-05-13 13:42 UTC, TheEmidee requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259)* status: all files reviewed, 3 unresolved discussions (waiting on @Fr0oZzFred, @MaxDaniels, and @ThibNach)

___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 17 at r4](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxlxBOaE629mJh4xFfs:-NxlxBOaE629mJh4xFft:b-iih41g) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/5a8eb1094623f5d2a7ed997b6e9dc2ffe301d375/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L17)):*
> ```cpp
> 
> bool bSplitActionBarIgnoreOptOut = false;
> #if !UE_BUILD_SHIPPING
> ```

in fact, surround with `#if !( UE_BUILD_SHIPPING || UE_BUILD_TEST )`
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 17 at r4](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxlxCcO8BUisrfjwaJW:-NxlxCcO8BUisrfjwaJX:b-r5zf16) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/5a8eb1094623f5d2a7ed997b6e9dc2ffe301d375/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L17)):*
> ```cpp
> 
> bool bSplitActionBarIgnoreOptOut = false;
> #if !UE_BUILD_SHIPPING
> ```

empty line above the macro
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 186 at r4](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxmAqhT4hpGxjhlPdSy:-NxmAqhT4hpGxjhlPdSz:bv3yave) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/5a8eb1094623f5d2a7ed997b6e9dc2ffe301d375/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L186)):*
> ```cpp
>     for ( const auto * local_player : sorted_players )
>     {
>         const auto * action_router = ULocalPlayer::GetSubsystem< UCommonUIActionRouterBase >( owning_local_player );
> ```

I meant:

```
    for ( const auto * local_player : sorted_players )
    {
        if ( local_player != owning_local_player || bDisplayOwningPlayerActionsOnly )
        {
            continue;
        }

        if ( !IsEntryClassValid( ActionButtonClass ) )
        {
            continue;
        }

        if ( const auto * action_router = ULocalPlayer::GetSubsystem< UCommonUIActionRouterBase >( owning_local_player ) )
        {
        }
    }
 }
```


<!-- Sent from Reviewable.io -->

2024-05-13 13:42 UTC, TheEmidee reviewed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259)* status: all files reviewed, 3 unresolved discussions (waiting on @Fr0oZzFred, @MaxDaniels, and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-05-13 14:58 UTC, ThibNach reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259)* status: all files reviewed, 3 unresolved discussions (waiting on @Fr0oZzFred, @MaxDaniels, and @TheEmidee)

___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 17 at r4](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxlxBOaE629mJh4xFfs:-NxmQBlY-Sj6O4_8nura:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/5a8eb1094623f5d2a7ed997b6e9dc2ffe301d375/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L17)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

in fact, surround with `#if !( UE_BUILD_SHIPPING || UE_BUILD_TEST )`
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 17 at r4](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxlxCcO8BUisrfjwaJW:-NxmQC1K4mV9tEzm5DwN:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/5a8eb1094623f5d2a7ed997b6e9dc2ffe301d375/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L17)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

empty line above the macro
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 186 at r4](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-NxmAqhT4hpGxjhlPdSy:-NxmRmto4P1u3zXGf1VQ:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/5a8eb1094623f5d2a7ed997b6e9dc2ffe301d375/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L186)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

I meant:

```
    for ( const auto * local_player : sorted_players )
    {
        if ( local_player != owning_local_player || bDisplayOwningPlayerActionsOnly )
        {
            continue;
        }

        if ( !IsEntryClassValid( ActionButtonClass ) )
        {
            continue;
        }

        if ( const auto * action_router = ULocalPlayer::GetSubsystem< UCommonUIActionRouterBase >( owning_local_player ) )
        {
        }
    }
 }
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-13 15:36 UTC, TheEmidee requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259)* status: all files reviewed, 1 unresolved discussion (waiting on @Fr0oZzFred, @MaxDaniels, and @ThibNach)

___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 189 at r5](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-Nxm_vBS1UGFbDOCPPhE:-Nxm_vBS1UGFbDOCPPhF:b-fzwuzz) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/e00a984c6ef813d3e2945a03fc8da5452f7118a1/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L189)):*
> ```cpp
>     for ( const auto * local_player : sorted_players )
>     {
>         if ( local_player != owning_local_player && bDisplayOwningPlayerActionsOnly )
> ```

I realize the condition is not correct now.

should be:

```
const auto is_player_valid = LocalPlayer == OwningLocalPlayer || !bDisplayOwningPlayerActionsOnly;

if ( ! is_player_valid )
{
    continue;
}
```


<!-- Sent from Reviewable.io -->

2024-05-13 18:00 UTC, ThibNach reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259)* status: all files reviewed, 1 unresolved discussion (waiting on @Fr0oZzFred, @MaxDaniels, and @TheEmidee)

___
*[`Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp` line 189 at r5](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259#-Nxm_vBS1UGFbDOCPPhE:-Nxn4Mm4Au0np_HYHX6t:bcqniyx) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/e00a984c6ef813d3e2945a03fc8da5452f7118a1/Source/GameBaseFramework/Private/GBFSplitCommonBoundActionBar.cpp#L189)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

I realize the condition is not correct now.

should be:

```
const auto is_player_valid = LocalPlayer == OwningLocalPlayer || !bDisplayOwningPlayerActionsOnly;

if ( ! is_player_valid )
{
    continue;
}
```
</blockquote></details>

If it's a question of style, I'll make the change tmrw morning but the condition is correct and works.(... I think... you make me doubt... x) )


<!-- Sent from Reviewable.io -->

2024-05-14 09:12 UTC, TheEmidee approved these changes
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/259)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fr0oZzFred and @MaxDaniels)



<!-- Sent from Reviewable.io -->

2024-05-14 09:14 UTC, merged