Abilityset blueprint functions
TheEmidee/UE4GameBaseFramework pull request #267
Opened 2024-05-28 16:00 UTC by VectorGamez

2024-05-28 16:04 UTC, MaxDaniels approved these changes, later dismissed

2024-05-29 08:13 UTC, TheEmidee requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/267)* status: all files reviewed, 2 unresolved discussions (waiting on @Fr0oZzFred, @ThibNach, and @VectorGamez)

___
*[`Source/GameBaseFramework/Public/GAS/Abilities/GBFAbilitySet.h` line 83 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/267#-Nz2PAu_COLBodxoY3NA:-Nz2PAu_COLBodxoY3NB:b-mu3adk) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/9d19466bf22cc91e504b0b5a254b16bc8ed62954/Source/GameBaseFramework/Public/GAS/Abilities/GBFAbilitySet.h#L83)):*
> ```objc
> public:
>     UFUNCTION( BlueprintCallable, BlueprintPure = false )
>     void GiveToAbilitySystem( UAbilitySystemComponent * asc, UPARAM( ref ) FGBFAbilitySet_GrantedHandles & out_granted_handles, UObject * source_object = nullptr ) const;
> ```

Prefix with K2_ to avoid any unintentional use in C++ (and use the Display Name to remove K2_)
___
*[`Source/GameBaseFramework/Public/GAS/Abilities/GBFAbilitySet.h` line 86 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/267#-Nz2PHUUADPFDArwnf5G:-Nz2PHUUADPFDArwnf5H:bb7od0r) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/9d19466bf22cc91e504b0b5a254b16bc8ed62954/Source/GameBaseFramework/Public/GAS/Abilities/GBFAbilitySet.h#L86)):*
> ```objc
> 
>     UFUNCTION( BlueprintCallable )
>     void TakeFromAbilitySystem( UAbilitySystemComponent * asc, UPARAM( ref ) FGBFAbilitySet_GrantedHandles & granted_handles );
> ```

same


<!-- Sent from Reviewable.io -->

2024-05-29 14:38 UTC, VectorGamez reviewed
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/267)* status: all files reviewed, 2 unresolved discussions (waiting on @Fr0oZzFred, @TheEmidee, and @ThibNach)

___
*[`Source/GameBaseFramework/Public/GAS/Abilities/GBFAbilitySet.h` line 83 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/267#-Nz2PAu_COLBodxoY3NA:-Nz3lXiC00HFJkAN8r2g:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/9d19466bf22cc91e504b0b5a254b16bc8ed62954/Source/GameBaseFramework/Public/GAS/Abilities/GBFAbilitySet.h#L83)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

Prefix with K2_ to avoid any unintentional use in C++ (and use the Display Name to remove K2_)
</blockquote></details>

Done.
___
*[`Source/GameBaseFramework/Public/GAS/Abilities/GBFAbilitySet.h` line 86 at r1](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/267#-Nz2PHUUADPFDArwnf5G:-Nz3lXw6973jbTkXT_3e:b-896fix) ([raw file](https://github.com/TheEmidee/UEGameBaseFramework/blob/9d19466bf22cc91e504b0b5a254b16bc8ed62954/Source/GameBaseFramework/Public/GAS/Abilities/GBFAbilitySet.h#L86)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-29 15:25 UTC, TheEmidee approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UEGameBaseFramework/267#-:-Nz3xBg01nUPaCwKR3H2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fr0oZzFred and @ThibNach)



<!-- Sent from Reviewable.io -->

2024-05-29 15:25 UTC, merged