Feature/world actor registry improvements
TheEmidee/UE4GameBaseFramework pull request #27
Opened 2021-05-07 09:47 UTC by VectorGamez

2021-05-18 20:23 UTC, TheEmidee requested changes

2021-05-18 20:23 UTC, TheEmidee commented on Source/GameBaseFramework/Public/GameBaseFrameworkSettings.h
> +    uint8 EnableWorldActorRegistry : 1;
bEnableWorldActorRegistry

2021-05-20 16:54 UTC, TheEmidee reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/theemidee/ue4gamebaseframework/27)* status: all files reviewed, 1 unresolved discussion (waiting on @VectorGamez)



<!-- Sent from Reviewable.io -->

2021-05-25 10:23 UTC, VectorGamez commented on Source/GameBaseFramework/Public/GameBaseFrameworkSettings.h
> +    uint8 EnableWorldActorRegistry : 1;
Done.

2021-05-27 07:43 UTC, TheEmidee approved these changes

2021-05-27 07:43 UTC, merged