Fix projectile overlap behaviour
TheEmidee/UE4GameBaseFramework pull request #282
Opened 2024-07-25 12:50 UTC by hadesfury

2024-07-25 19:06 UTC, TheEmidee requested changes

2024-07-25 19:06 UTC, TheEmidee commented on Source/GameBaseFramework/Private/GAS/Projectiles/GBFProjectile.cpp
> +    IsInOverlap = false;
can you rename to `bIsInOverlap` ?

2024-07-25 19:06 UTC, TheEmidee commented on Source/GameBaseFramework/Private/GAS/Projectiles/GBFProjectile.cpp
> +        hit_result = FHitResult( other_actor, other_component, FVector3d::Zero(), FVector3d::Zero() );
`FVector`, not `FVector3d`

2024-07-26 07:05 UTC, VectorGamez requested changes

2024-07-26 07:05 UTC, VectorGamez commented on Source/GameBaseFramework/Private/GAS/Projectiles/GBFProjectile.cpp
> +    if ( ImpactDetectionType == EGBFProjectileImpactDetectionType::Overlap && hit_result.GetActor() == nullptr )
ImpactDetectionType will always be overlap here. You can remove it

2024-07-26 20:25 UTC, TheEmidee approved these changes

2024-07-26 20:25 UTC, merged