Gbf simplechar params
TheEmidee/UE4GameBaseFramework pull request #291
Opened 2024-08-29 12:10 UTC by jagged-teeth

2024-08-29 15:29 UTC, VectorGamez requested changes
I think the PR is not on the correct base

2024-08-29 19:13 UTC, TheEmidee commented on Source/GameBaseFramework/Public/Characters/GBFSimpleCharacterWithAbilities.h
> +    UPROPERTY( EditInstanceOnly )
they all should be `EditAnywhere`

2024-08-30 07:07 UTC, VectorGamez approved these changes, later dismissed

2024-09-02 06:27 UTC, jagged-teeth commented on Source/GameBaseFramework/Public/Characters/GBFSimpleCharacterWithAbilities.h
> +    UPROPERTY( EditInstanceOnly )
Ok, i only left ```    UPROPERTY( Transient )
    TArray< TObjectPtr< UAttributeSet > > AttributeSets;```

2024-09-02 06:45 UTC, VectorGamez approved these changes

2024-09-02 07:54 UTC, merged