New ability task to activate an ability from an event, and wait for it to be finished
TheEmidee/UE4GameBaseFramework pull request #292
Opened 2024-08-30 13:19 UTC by TheEmidee

2024-08-30 13:51 UTC, VectorGamez requested changes

2024-08-30 13:51 UTC, VectorGamez commented on Source/GameBaseFramework/Private/GAS/Tasks/GBFAT_ActivateAbilityFromEvent.cpp
> +    const auto asc_to_use = OptionalAbilitySystemComponent != nullptr ? OptionalAbilitySystemComponent : AbilitySystemComponent;
auto *

2024-08-30 13:51 UTC, VectorGamez commented on Source/GameBaseFramework/Public/GAS/Tasks/GBFAT_ActivateAbilityFromEvent.h
> +    UFUNCTION()
UFUNCTION's before non- UFUNCTION's

2024-09-02 06:47 UTC, Fr0oZzFred approved these changes, later dismissed

2024-09-04 07:53 UTC, merged