feature/trigger_manaer_new_activation_policies
TheEmidee/UE4GameBaseFramework pull request #42
Opened 2022-03-25 13:40 UTC by VectorGamez

2022-03-31 20:18 UTC, TheEmidee requested changes

2022-03-31 20:18 UTC, TheEmidee commented on Source/GameBaseFramework/Public/Tasks/GBFAT_MonitorTriggerManager.h
> +class GAMEBASEFRAMEWORK_API UGBFAT_MonitorTriggerManager : public UAbilityTask
I thought I had proposed that before, but what about you rename to WaitForTriggerManagerEvent ?
Most (if not all) of the tasks in UE start with Wait

2022-04-01 09:02 UTC, VectorGamez commented on Source/GameBaseFramework/Public/Tasks/GBFAT_MonitorTriggerManager.h
> +class GAMEBASEFRAMEWORK_API UGBFAT_MonitorTriggerManager : public UAbilityTask
Done.

2022-04-01 10:31 UTC, TheEmidee approved these changes

2022-04-01 10:31 UTC, merged