Feature/gbftriggerbox2
TheEmidee/UE4GameBaseFramework pull request #46
Opened 2022-04-11 10:29 UTC by VectorGamez

2022-04-13 15:32 UTC, TheEmidee commented on Source/GameBaseFramework/Public/Gameplay/GBFTriggerBox.h
> +// Fill out your copyright notice in the Description page of Project Settings.
remove

2022-04-13 15:32 UTC, TheEmidee requested changes

2022-04-13 15:32 UTC, TheEmidee commented on Source/GameBaseFramework/Public/Gameplay/GBFTriggerBox.h
> +#include "CoreMinimal.h"
<>

2022-04-13 15:32 UTC, TheEmidee commented on Source/GameBaseFramework/Public/Gameplay/GBFTriggerBox.h
> +// Fill out your copyright notice in the Description page of Project Settings.
Remove

2022-04-13 15:32 UTC, TheEmidee commented on Source/GameBaseFramework/Public/Gameplay/GBFTriggerBox.h
> +#include "GameFramework/Actor.h"
<>

2022-04-14 07:18 UTC, VectorGamez commented on Source/GameBaseFramework/Public/Gameplay/GBFTriggerBox.h
> +#include "GameFramework/Actor.h"
Done.

2022-04-14 07:19 UTC, VectorGamez commented on Source/GameBaseFramework/Public/Gameplay/GBFTriggerBox.h
> +#include "CoreMinimal.h"
Done.

2022-04-14 07:19 UTC, VectorGamez commented on Source/GameBaseFramework/Public/Gameplay/GBFTriggerBox.h
> +// Fill out your copyright notice in the Description page of Project Settings.
Done.

2022-04-14 07:44 UTC, TheEmidee approved these changes

2022-04-14 07:44 UTC, merged